/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_haw_smartshelf_reader_test_ICodeReaderTest */

#ifndef _Included_de_haw_smartshelf_reader_test_ICodeReaderTest
#define _Included_de_haw_smartshelf_reader_test_ICodeReaderTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_haw_smartshelf_reader_test_ICodeReaderTest
 * Method:    CRM_init
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_de_haw_smartshelf_reader_test_ICodeReaderTest_CRM_1init
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
