package de.haw.smartshelf.db.data.pers;
// Generated 02.11.2007 15:27:42 by Hibernate Tools 3.2.0.b11



/**
 * ArticleExtension generated by hbm2java
 */
public class ArticleExtension  implements java.io.Serializable {


     private ArticleExtensionId id;
     private Article article;

    public ArticleExtension() {
    }

    public ArticleExtension(ArticleExtensionId id, Article article) {
       this.id = id;
       this.article = article;
    }
   
    public ArticleExtensionId getId() {
        return this.id;
    }
    
    public void setId(ArticleExtensionId id) {
        this.id = id;
    }
    public Article getArticle() {
        return this.article;
    }
    
    public void setArticle(Article article) {
        this.article = article;
    }




}


