package de.haw.smartshelf.db.data.pers;
// Generated 30.10.2007 16:56:44 by Hibernate Tools 3.2.0.b11



/**
 * ArticleLocation generated by hbm2java
 */
public class ArticleLocation  implements java.io.Serializable {


     private ArticleLocationId id;
     private Article article;
     private Shelf shelf;

    public ArticleLocation() {
    }

	
    public ArticleLocation(ArticleLocationId id) {
        this.id = id;
    }
    public ArticleLocation(ArticleLocationId id, Article article, Shelf shelf) {
       this.id = id;
       this.article = article;
       this.shelf = shelf;
    }
   
    public ArticleLocationId getId() {
        return this.id;
    }
    
    public void setId(ArticleLocationId id) {
        this.id = id;
    }
    public Article getArticle() {
        return this.article;
    }
    
    public void setArticle(Article article) {
        this.article = article;
    }
    public Shelf getShelf() {
        return this.shelf;
    }
    
    public void setShelf(Shelf shelf) {
        this.shelf = shelf;
    }




}


