CREATE TABLE ARTICLE (
    RFID INT NOT NULL PRIMARY KEY,
	ARTICLE_TYPE VARCHAR(200)
);

CREATE TABLE ARTICLE_EXTENSIONS (
    RFID INT NOT NULL,
	NAME VARCHAR(200),
	VALUE TEXT,
	FOREIGN KEY (RFID) REFERENCES ARTICLE (RFID) ON DELETE CASCADE
);
