package de.haw.smartshelf.db.data.pers;
// Generated 02.11.2007 15:27:42 by Hibernate Tools 3.2.0.b11



/**
 * ArticleLocationId generated by hbm2java
 */
public class ArticleLocationId  implements java.io.Serializable {


     private String rfid;
     private String shelf;
     private String cell;
     private String position;

    public ArticleLocationId() {
    }

    public ArticleLocationId(String rfid, String shelf, String cell, String position) {
       this.rfid = rfid;
       this.shelf = shelf;
       this.cell = cell;
       this.position = position;
    }
   
    public String getRfid() {
        return this.rfid;
    }
    
    public void setRfid(String rfid) {
        this.rfid = rfid;
    }
    public String getShelf() {
        return this.shelf;
    }
    
    public void setShelf(String shelf) {
        this.shelf = shelf;
    }
    public String getCell() {
        return this.cell;
    }
    
    public void setCell(String cell) {
        this.cell = cell;
    }
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArticleLocationId) ) return false;
		 ArticleLocationId castOther = ( ArticleLocationId ) other; 
         
		 return ( (this.getRfid()==castOther.getRfid()) || ( this.getRfid()!=null && castOther.getRfid()!=null && this.getRfid().equals(castOther.getRfid()) ) )
 && ( (this.getShelf()==castOther.getShelf()) || ( this.getShelf()!=null && castOther.getShelf()!=null && this.getShelf().equals(castOther.getShelf()) ) )
 && ( (this.getCell()==castOther.getCell()) || ( this.getCell()!=null && castOther.getCell()!=null && this.getCell().equals(castOther.getCell()) ) )
 && ( (this.getPosition()==castOther.getPosition()) || ( this.getPosition()!=null && castOther.getPosition()!=null && this.getPosition().equals(castOther.getPosition()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRfid() == null ? 0 : this.getRfid().hashCode() );
         result = 37 * result + ( getShelf() == null ? 0 : this.getShelf().hashCode() );
         result = 37 * result + ( getCell() == null ? 0 : this.getCell().hashCode() );
         result = 37 * result + ( getPosition() == null ? 0 : this.getPosition().hashCode() );
         return result;
   }   


}


