package de.haw.smartshelf.db.data.pers;
// Generated 30.10.2007 16:56:44 by Hibernate Tools 3.2.0.b11


import java.util.HashSet;
import java.util.Set;

/**
 * Article generated by hbm2java
 */
public class Article  implements java.io.Serializable {


     private String rfid;
     private String articleType;
     private Set articleLocations = new HashSet(0);
     private Set articleExtensionses = new HashSet(0);

    public Article() {
    }

	
    public Article(String rfid) {
        this.rfid = rfid;
    }
    public Article(String rfid, String articleType, Set articleLocations, Set articleExtensionses) {
       this.rfid = rfid;
       this.articleType = articleType;
       this.articleLocations = articleLocations;
       this.articleExtensionses = articleExtensionses;
    }
   
    public String getRfid() {
        return this.rfid;
    }
    
    public void setRfid(String rfid) {
        this.rfid = rfid;
    }
    public String getArticleType() {
        return this.articleType;
    }
    
    public void setArticleType(String articleType) {
        this.articleType = articleType;
    }
    public Set getArticleLocations() {
        return this.articleLocations;
    }
    
    public void setArticleLocations(Set articleLocations) {
        this.articleLocations = articleLocations;
    }
    public Set getArticleExtensionses() {
        return this.articleExtensionses;
    }
    
    public void setArticleExtensionses(Set articleExtensionses) {
        this.articleExtensionses = articleExtensionses;
    }

    @Override
	public String toString()
	{
		return "RFID: " + getRfid() + " TYPE: " + getArticleType();
	}


}


