package de.haw.smartshelf.db.data.pers;
// Generated 02.11.2007 15:27:42 by Hibernate Tools 3.2.0.b11


import java.util.HashSet;
import java.util.Set;

/**
 * Article generated by hbm2java
 */
public class Article  implements java.io.Serializable {


     private String rfid;
     private String articleType;
     private Set articleLocations = new HashSet(0);
     private Set articleExtensions = new HashSet(0);

    public Article() {
    }

	
    public Article(String rfid) {
        this.rfid = rfid;
    }
    public Article(String rfid, String articleType, Set articleLocations, Set articleExtensions) {
       this.rfid = rfid;
       this.articleType = articleType;
       this.articleLocations = articleLocations;
       this.articleExtensions = articleExtensions;
    }
   
    public String getRfid() {
        return this.rfid;
    }
    
    public void setRfid(String rfid) {
        this.rfid = rfid;
    }
    public String getArticleType() {
        return this.articleType;
    }
    
    public void setArticleType(String articleType) {
        this.articleType = articleType;
    }
    public Set getArticleLocations() {
        return this.articleLocations;
    }
    
    public void setArticleLocations(Set articleLocations) {
        this.articleLocations = articleLocations;
    }
    public Set getArticleExtensions() {
        return this.articleExtensions;
    }
    
    public void setArticleExtensions(Set articleExtensions) {
        this.articleExtensions = articleExtensions;
    }




}


