package de.haw.smartshelf.db.data.pers;

// Generated 28.10.2007 11:58:49 by Hibernate Tools 3.2.0.b11

/**
 * ArticleExtensionsId generated by hbm2java
 */
public class ArticleExtensionsId implements java.io.Serializable
{
	private static final long serialVersionUID = -3577907439410089218L;
	
	private int rfid;
	private String name;
	private String value;

	public ArticleExtensionsId()
	{
	}

	public ArticleExtensionsId(int rfid)
	{
		this.rfid = rfid;
	}

	public ArticleExtensionsId(int rfid, String name, String value)
	{
		this.rfid = rfid;
		this.name = name;
		this.value = value;
	}

	public int getRfid()
	{
		return this.rfid;
	}

	public void setRfid(int rfid)
	{
		this.rfid = rfid;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getValue()
	{
		return this.value;
	}

	public void setValue(String value)
	{
		this.value = value;
	}

	public boolean equals(Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArticleExtensionsId))
			return false;
		ArticleExtensionsId castOther = (ArticleExtensionsId) other;

		return (this.getRfid() == castOther.getRfid())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null && this
						.getName().equals(castOther.getName())))
				&& ((this.getValue() == castOther.getValue()) || (this.getValue() != null
						&& castOther.getValue() != null && this.getValue().equals(castOther.getValue())));
	}

	public int hashCode()
	{
		int result = 17;

		result = 37 * result + this.getRfid();
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getValue() == null ? 0 : this.getValue().hashCode());
		return result;
	}

	@Override
	public String toString()
	{
		return "EXTENSION RFID: " + getRfid() + " NAME: " + getName() + " VALUE " + getValue();
	}
}
