package de.haw.smartshelf.db.data.pers;
// Generated 30.10.2007 16:56:44 by Hibernate Tools 3.2.0.b11



/**
 * ArticleExtensions generated by hbm2java
 */
public class ArticleExtensions  implements java.io.Serializable {


     private ArticleExtensionsId id;
     private Article article;

    public ArticleExtensions() {
    }

    public ArticleExtensions(ArticleExtensionsId id, Article article) {
       this.id = id;
       this.article = article;
    }
   
    public ArticleExtensionsId getId() {
        return this.id;
    }
    
    public void setId(ArticleExtensionsId id) {
        this.id = id;
    }
    public Article getArticle() {
        return this.article;
    }
    
    public void setArticle(Article article) {
        this.article = article;
    }
    
    @Override
	public String toString()
	{
		return getId().toString();
	}
}


