package de.haw.smartshelf.db.data.pers;
// Generated 02.11.2007 15:27:42 by Hibernate Tools 3.2.0.b11


import java.util.HashSet;
import java.util.Set;

/**
 * Shelf generated by hbm2java
 */
public class Shelf  implements java.io.Serializable {


     private String id;
     private String name;
     private String location;
     private Set articleLocations = new HashSet(0);

    public Shelf() {
    }

	
    public Shelf(String id) {
        this.id = id;
    }
    public Shelf(String id, String name, String location, Set articleLocations) {
       this.id = id;
       this.name = name;
       this.location = location;
       this.articleLocations = articleLocations;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public Set getArticleLocations() {
        return this.articleLocations;
    }
    
    public void setArticleLocations(Set articleLocations) {
        this.articleLocations = articleLocations;
    }




}


