CREATE TABLE ARTICLE 
(
    RFID VARCHAR(50) NOT NULL PRIMARY KEY,
	ARTICLE_TYPE VARCHAR(200)
);

CREATE TABLE ARTICLE_EXTENSIONS 
(
    RFID VARCHAR(50) NOT NULL,
	NAME VARCHAR(200),
	VALUE TEXT,
	FOREIGN KEY (RFID) REFERENCES ARTICLE (RFID) ON DELETE CASCADE
);

CREATE TABLE SHELF 
(
    ID INT NOT NULL PRIMARY KEY,
	NAME VARCHAR(100),
	LOCATION VARCHAR(150)
);

CREATE TABLE ARTICLE_LOCATION 
(
    RFID VARCHAR(50),
	SHELF INT,
	CELL VARCHAR(50),
	POSITION VARCHAR(50),
	UNIQUE(RFID, SHELF),
	FOREIGN KEY (RFID) REFERENCES ARTICLE (RFID) ON DELETE CASCADE,
	FOREIGN KEY (SHELF) REFERENCES SHELF (ID) ON DELETE CASCADE
);
